### ISSUE TITLE
provide tree_string with override=False

### ISSUE THREAD

**Issue by timvgl** [mrschweizer/PyThat#11]
Hi,
I am using tree_string for my analyzing tool.
Unfortuantly I have to overwrite the nc file each time if I want to get tree_string which costs - depending on the file size - a lot of time.
Is it possible to load tree_string everytime?
Thank you

**Comment by mrschweizer** [comment]
This will be worked on in the near future.
In general, much more meta data will be copied from .h5 to .nc files.
1) MeaturementTree.tree_string, ,labbook,  ,definition, devices, labbook, logs
2) The name of the row will be included as attribute in the .nc data_vars in order to allow for easier identification

**Comment by mrschweizer** [comment]
Update: xarray attrs does not support dict class objects. This makes the whole thing more difficult.

**Comment by mrschweizer** [comment]
Update: netCDF files do not support the serialization of dict type objects. This makes the whole story a bit more difficult.
